#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    ssh-authorized-keys:
      - ssh-rsa AAAAB3...YourPublicKeyHere
runcmd:
  - echo "Cloud-init executed" >> /var/log/cloud-init.log
