#cloud-config
hostname: k8s-master
manage_etc_hosts: true

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAA...your-public-key...xyz

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - curl
  - apt-transport-https
  - ca-certificates
  - software-properties-common

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - modprobe br_netfilter
  - sysctl -w net.ipv4.ip_forward=1
  - echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
  - sysctl --system
  - apt-get update && apt-get install -y kubeadm kubelet kubectl
  - kubeadm init --pod-network-cidr=192.168.0.0/16
  - mkdir -p /home/ubuntu/.kube
  - cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
  - chown ubuntu:ubuntu /home/ubuntu/.kube/config
